### ISSUE TITLE
Development instructions fail

### ISSUE THREAD

**Issue by karel1980** [JosePedroDias/aframe-extrude-and-lathe#3]
The development instructions for various reasons;
First hurdle was I didn't have http-server installed with npm -g.

**Comment by karel1980** [comment]
Next hurdle: npm run build step fails. See output:

` 💩  ~/work/personal/aframe-extrude-and-lathe/examples
± |fix/missing-httpserver ✗| → npm run build

> @ build /Users/karelvervaeke/work/personal/aframe-extrude-and-lathe/examples
> browserify main.js -o build.js

Error: Cannot find module '../node_modules/three-dev/examples/js/loaders/OBJLoader' from '/Users/karelvervaeke/work/personal/aframe-extrude-and-lathe/examples/node_modules/aframe-core/lib'
    at /Users/karelvervaeke/work/personal/aframe-extrude-and-lathe/examples/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/karelvervaeke/work/personal/aframe-extrude-and-lathe/examples/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/karelvervaeke/work/personal/aframe-extrude-and-lathe/examples/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/karelvervaeke/work/personal/aframe-extrude-and-lathe/examples/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
`

Workaround is to run npm install in examples/node_modules/aframe-core first (if I recall correctly).

aframe-core/package.json, hints at a possible solution: it says that aframe-core has been merged into the aframe repo. I'll try updating dependencies.

**Comment by karel1980** [comment]
I didn't manage to fix it yet & have to start working on my day job.
Partial progress (changed dependencies & fixed warnings, but nothing renders):
https://github.com/karel1980/aframe-extrude-and-lathe/tree/fix/issue-3-aframe-core
